package com.jerry.baselib.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jerry.baselib.common.bean.Order;
import com.jerry.baselib.common.bean.Product;
import com.jerry.baselib.common.bean.ScriptWord;

import com.jerry.baselib.greendao.OrderDao;
import com.jerry.baselib.greendao.ProductDao;
import com.jerry.baselib.greendao.ScriptWordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig scriptWordDaoConfig;

    private final OrderDao orderDao;
    private final ProductDao productDao;
    private final ScriptWordDao scriptWordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        scriptWordDaoConfig = daoConfigMap.get(ScriptWordDao.class).clone();
        scriptWordDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        scriptWordDao = new ScriptWordDao(scriptWordDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(Product.class, productDao);
        registerDao(ScriptWord.class, scriptWordDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
        scriptWordDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public ScriptWordDao getScriptWordDao() {
        return scriptWordDao;
    }

}
