package com.jerry.baselib.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jerry.baselib.common.bean.XyProduct;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "XY_PRODUCT".
*/
public class XyProductDao extends AbstractDao<XyProduct, Void> {

    public static final String TABLENAME = "XY_PRODUCT";

    /**
     * Properties of entity XyProduct.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Title = new Property(0, String.class, "title", false, "TITLE");
        public final static Property Price = new Property(1, String.class, "price", false, "PRICE");
        public final static Property Picture = new Property(2, String.class, "picture", false, "PICTURE");
    }


    public XyProductDao(DaoConfig config) {
        super(config);
    }
    
    public XyProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"XY_PRODUCT\" (" + //
                "\"TITLE\" TEXT," + // 0: title
                "\"PRICE\" TEXT," + // 1: price
                "\"PICTURE\" TEXT);"); // 2: picture
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"XY_PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, XyProduct entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(3, picture);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, XyProduct entity) {
        stmt.clearBindings();
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(1, title);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(2, price);
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(3, picture);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public XyProduct readEntity(Cursor cursor, int offset) {
        XyProduct entity = new XyProduct( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // title
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // price
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // picture
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, XyProduct entity, int offset) {
        entity.setTitle(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPrice(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPicture(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(XyProduct entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(XyProduct entity) {
        return null;
    }

    @Override
    public boolean hasKey(XyProduct entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
